Retail-Product-Management-main/E-Commerce-Portal/E-Commerce-Portal/Controllers/ECommerceController.cs
using E_Commerce_Portal.Models;
using E_Commerce_Portal.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Portal.Controllers
{
    public class ECommerceController : Controller
    {

        private readonly IRepository repo;
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ECommerceController));



        public ECommerceController(IRepository _repo)
        {

            repo = _repo;
            _log4net.Info("Logger in ECommerce");
        }


        public IActionResult Index()
        {
            List<Product> products = new List<Product>();

            string token = HttpContext.Session.GetString("token");
            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            _log4net.Info("User is seeing products");

            try {
                products = repo.GetProducts(token);
            }
            catch (Exception)
            {
                _log4net.Info("Service is down");
            }
            

            return View(products);
        }

        // Search for a product
        [HttpGet]
        public IActionResult Search(int option, string productNameOrId)
        {
            string token = HttpContext.Session.GetString("token");

            List<Product> products = repo.GetProducts(token);

            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }

            if (option == 2)
            {
                _log4net.Info("User is Searching product by Id");

                if (Int32.Parse(productNameOrId) > 0)
                {
                    products = repo.GetProductsById(token, Int32.Parse(productNameOrId));
                }

                return View("Details", products);
            }

            _log4net.Info("User is Searching product by Name");

            if (!String.IsNullOrEmpty(productNameOrId))
            {
                products = repo.GetProductsByName(token, productNameOrId);
            }

            return View("Details", products);
        }

        [HttpPost]
        public IActionResult AddRating(int productId, int rate)
        {
            string token = HttpContext.Session.GetString("token");

            if (token == null)
            {
                _log4net.Info("User is not logged in");
                ViewBag.Message = "Please Login First";
                return RedirectToAction("Index", "Login");
            }
            ViewBag.Id = productId;
            ViewBag.rating = rate;
            var val = repo.AddRating(token, productId, rate);

            if (val)
                return RedirectToAction("Index");
            else
                return BadRequest("Not able to add rating");
        }




    }

}

Retail-Product-Management-main/E-Commerce-Portal/E-Commerce-Portal/Controllers/HomeController.cs
using E_Commerce_Portal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Portal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



    }
}

Retail-Product-Management-main/E-Commerce-Portal/E-Commerce-Portal/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home Page"; }



<div class="text-center align-content-center">
    <h1 class="display-4">Welcome to E-Commerce</h1>
    <p><a asp-controller="ECommerce" asp-action="Index">Shop Now</a></p>
</div>
<hr />
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img width="500" height="600" class="d-block w-100" src="~/image/1.jpg" alt="First slide">

        </div>
        <div class="carousel-item">

            <img width="500" height="600" class="d-block w-100" src="~/image/2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img width="500" height="600" class="d-block w-100" src="~/image/earphone.webp" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<br />